# Generated by Django 5.0.1 on 2024-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Dnevni', 'Dnevni'), ('Tjedni', 'Tjedni'), ('Mjesecni', 'Mjesecni')], max_length=50),
        ),
    ]
