# Generated by Django 5.0.1 on 2024-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Dnevni', 'Dnevni'), ('Tjedni', 'Tjedni'), ('Mjesečni', 'Mjesecni'), ('Godišnji', 'Godišnji')], max_length=50),
        ),
    ]
